site_url: /
logo_url: /logo.svg

locale: vi

backend:
  name: git-gateway
  branch: master

media_folder: static/images/uploads
public_folder: /images/uploads

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: 'post'
    label: 'Bài viết'
    folder: 'posts'
    create: true
    slug: '{{fields.slug}}'
    path: '{{slug}}/index'
    editor:
      preview: false
    fields:
      - name: 'title'
        label: 'Tựa đề'
        widget: 'string'
        required: true
      - name: 'datetime'
        label: 'Thời gian'
        widget: 'datetime'
        required: true
      - name: 'slug'
        label: 'Đường dẫn'
        widget: 'string'
        required: true
      - name: 'poster'
        label: 'Hình đại diện'
        widget: 'object'
        fields:
          - name: 'local'
            label: 'Tải lên'
            widget: 'image'
            required: false
          - name: 'external'
            label: 'Liên kết ngoài'
            widget: 'string'
            required: false
          - name: 'alt'
            label: 'Nội dung thay thế'
            widget: 'string'
            required: false
          - name: 'title'
            label: 'Tựa đề'
            widget: 'string'
            required: false
      - name: 'body'
        label: 'Nội dung bài viết'
        widget: 'markdown'
        required: true
