backend:
  name: git-gateway
  branch: master

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: 'post'
    label: 'Q'
    folder: 'posts'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - name: 'title'
        label: 'Title'
        widget: 'string'
        required: true
      - name: 'datetime'
        label: 'Publish Date'
        widget: 'datetime'
        required: true
      - name: 'slug'
        label: 'Path'
        widget: 'string'
        required: true
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
        required: true
