backend:
  name: git-gateway
  branch: master

media_folder: static/images/uploads
public_folder: /images/uploads

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: 'post'
    label: 'Post'
    folder: 'posts'
    create: true
    slug: '{{fields.slug}}'
    path: '{{slug}}/index'
    editor:
      preview: false
    fields:
      - name: 'title'
        label: 'Title'
        widget: 'string'
        required: true
      - name: 'datetime'
        label: 'Publish Date'
        widget: 'datetime'
        required: true
      - name: 'slug'
        label: 'Path'
        widget: 'string'
        required: true
      - name: 'poster'
        label: 'Poster'
        widget: 'object'
        fields:
          - name: 'src'
            label: 'Image'
            widget: 'image'
          - name: 'alt'
            label: 'Alt'
            widget: 'string'
          - name: 'title'
            label: 'Title'
            widget: 'string'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
        required: true
